### PR TITLE
feat: added support for all Weaviate HNSW configuration parameters

### PR DESCRIPTION
**Pull request by jjlatval**
The biggest reason for this PR is to enable DocArray to import large datasets (2M+ objects) to Weaviate backend (see https://weaviate.io/developers/weaviate/current/architecture/resources.html#imports-slowed-down-after-crossing-2m-objects---what-can-i-do). The current implementation does not allow passing relevant configuration parameters for Weaviate.

This PR adds support for all currently listed Weaviate HNSW parameters based on the documentation available here: https://weaviate.io/developers/weaviate/current/vector-index-plugins/hnsw.html#how-to-use-hnsw-and-parameters

### CODE REVIEW

**Comment by davidbp** [comment]
Thanks a lot for your PR.

**Comment by jjlatval** [comment]
> Seems that black test is not passing. Could you run `black --skip-string-normalization docarray/array/storage/weaviate/backend.py` and commit again `backend.py`?

The test should now pass

**Comment by alaeddine-13** [comment]
hey @jjlatval , thank you for your contribution. Can you cover the new parameters in the tests in `tests/unit/array/test_backend_configuration.py` ?

**Comment by davidbp** [comment]
Hello, now it seems you need to `black --skip-string-normalization` to the file`  test_backend_configuration.py`

**Pull request merged**
