### PR TITLE
feat: allow pass parameters to load_uri_to*

### PR DESCRIPTION
**Pull request by JoanFM**
Goals:

Capture properly Exceptions from `load_to_uri*` methods and allow to pass extra keyword arguments as `timeout`

### CODE REVIEW

**Review by TEChopra1000 — COMMENTED** [review]
This looks good. Thanks for the quick turn around! Do you think a try/exception statement would help with error handling?

**Comment by JoanFM** [comment]
> This looks good. Thanks for the quick turn around! Do you think a try/exception statement would help with error handling? I.e. #549

Hey @TEChopra1000,

This should not affect, since the Exceptions should be directly raised.

**Comment by samsja** [comment]
What if someone want to change a parameters from another function that is called inside this one ?

In this pr we only assume that user would only want to change `urllib.request.urlopen` parameters but why not could he want to change `req = urllib.request.Request` as well for instance ?

**Comment by JoanFM** [comment]
> What if someone want to change a parameters from another function that is called inside this one ?
> 
> In this pr we only assume that user would only want to change `urllib.request.urlopen` parameters but why not could he want to change `req = urllib.request.Request` as well for instance ?

Do you suggest simply to add timeout to `_uri_to_blob` but keep `**kwargs` in the API public functions?

**Review by samsja — APPROVED** [review]

**Pull request merged**
