### PR TITLE
Updated docs with conda install option

### LINKED ISSUE #21: Add a `conda` install option for `docarray`
It will be nice to have a conda install option. I have started the work already to add docarray to conda-forge channel. The PR (https://github.com/conda-forge/staged-recipes/pull/17482) was just merged. Give it 2-3 hours and you should be able to install the library with:

```sh
conda install -c conda-forge docarray
```

I will push a PR to update the docs soon.

### PR DESCRIPTION
**Pull request by sugatoray**
Updated docs. This PR is representative (qualitatively) of the work involved in the PR (https://github.com/conda-forge/staged-recipes/pull/17482) to add docarray to conda-forge channel.

- [x] readme (install instruction + badges)
- [x] docs (index.md: conda install only)

This closes #21 .

### CODE REVIEW

**Comment by hanxiao** [comment]
great work! should i merge after https://github.com/conda-forge/staged-recipes/pull/17482 is merged, right?

**Comment by hanxiao** [comment]
btw could you do 

```bash
git commit --amend
```

and fix your commit to `build: add conda-install`

then `git push --force`

**Comment by sugatoray** [comment]
> great work! should i merge after [conda-forge/staged-recipes#17482](https://github.com/conda-forge/staged-recipes/pull/17482) is merged, right?

You can go ahead even now. It is already available (by the time I opened the issue, the conda-forge PR was already merged).

```sh
$ conda search -c conda-forge docarray
Loading channels: done
# Name                       Version           Build  Channel             
docarray                       0.1.2    pyhd8ed1ab_0  conda-forge
```

**Comment by sugatoray** [comment]
I could not get time to amend the comment yet. I will do it tomorrow.

**Comment by sugatoray** [comment]
Hi @hanxiao,

There was another typo in the badges. Fixed it and committed the update with the comment you had suggested. Looks like there is a conflict. Please feel free to make changes as you see fit.

**Pull request closed without merging**
