### PR TITLE
fix(sqlite): persist offset2id only in destructor and context manager

### PR DESCRIPTION
**Pull request by alaeddine-13**

### CODE REVIEW

**Review by hanxiao — CHANGES_REQUESTED** [review]
let's hold it for now

**Comment by JoanFM** [comment]
Hey @alaeddine-13 could you fill more details of the issue and what is the problem and why is this a good solution?

**Review by JoanFM — CHANGES_REQUESTED** [review]
Please add details

**Comment by JoanFM** [comment]
Closing until further notice

**Pull request closed without merging**
