### PR TITLE
fix(array): fix add not performing deep copy

### PR DESCRIPTION
**Pull request by Jackmin801**
Goals:

- [x] Fix https://github.com/jina-ai/docarray/issues/545
- [x] check and update documentation, if required. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#documentation-guidelines)

### CODE REVIEW

**Comment by Jackmin801** [comment]
There is another occurrence of this [code](https://github.com/jina-ai/docarray/blob/main/docarray/array/base.py#L16). Might want to fix that one too.
But I don't know where this is used though. Wouldn't be able to test it.

**Review by alaeddine-13 — APPROVED** [review]
Thanks for your contribution, lgtm, will check if CI is passing

**Comment by alaeddine-13** [comment]
@Jackmin801  it looks like some tests are failing in tests/unit/document/test_plot.py, can you take a look ?

**Comment by Jackmin801** [comment]
Is the large drop in codecov normal? Not familiar with using codecov but looks pretty alarming to me.
How would I go about figuring out why the codecov dropped so much?

**Pull request merged**
