### PR TITLE
feat: make distance metric configurable in Weaviate backend

### LINKED ISSUE #358: Configure Distance Metric in Weaviate
As discussed over Slack, when Weaviate supports different distance metrics other than `cosine` they need to be configurable in doc array as well.

### PR DESCRIPTION
**Pull request by etiennedi**
Goals:

- [x] Allow configuring weaviate distance metric
- [x] check and update documentation, if required. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#documentation-guidelines)
- fixes #358

### CODE REVIEW

**Comment by etiennedi** [comment]
This is in draft state for now, because the linked Weaviate version `1.13.2` is not publicly available yet.

**Comment by davidbp** [comment]
thanks a lot!

**Comment by alaeddine-13** [comment]
Hey @etiennedi is the weaviate client also supposed to be upgraded ?

**Comment by etiennedi** [comment]
> Hey @etiennedi is the weaviate client also supposed to be upgraded ?

No changes are needed for this to work, but in case we are not yet on the latest, I would still recommend upgrading.

**Comment by etiennedi** [comment]
> thanks a lot! Please let us know when 1.13.2 is available so that we can test it.

My pleasure! Will do. Was supposed to be live already, but we caught one more bug in the final test pipeline. I'll keep you in the loop.

**Comment by etiennedi** [comment]
The version is available, I've converted to ready-for-review.

I can see that the linter failed on CI, any hints on where/how to fix this are appreciated. Merci.

**Comment by alaeddine-13** [comment]
Hey @etiennedi , you need to properly format the commit message, you can follow this guide: https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#writing-your-commit-message
Alternatively, you can give me permissions to force push in your branch, I can edit the commit message

**Review by davidbp — APPROVED** [review]
LGTM

**Review by alaeddine-13 — APPROVED** [review]
LGTM

**Pull request merged**
